openapi: 3.0.3
info:
  title: Payment Platform SALE API
  version: 1.0.0
  description: >
    API for SALE request to perform immediate payment (SALE) or authorization only (AUTH) transactions.

paths:
  /sale:
    post:
      summary: Perform SALE or AUTH transaction
      operationId: saleTransaction
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SaleRequest'
      responses:
        '200':
          description: Transaction response
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: '#/components/schemas/SaleSuccessResponse'
                  - $ref: '#/components/schemas/SaleDeclinedResponse'
                  - $ref: '#/components/schemas/SaleRedirectResponse'
                  - $ref: '#/components/schemas/SaleUndefinedResponse'
                discriminator:
                  propertyName: result
                  mapping:
                    SUCCESS: '#/components/schemas/SaleSuccessResponse'
                    DECLINED: '#/components/schemas/SaleDeclinedResponse'
                    REDIRECT: '#/components/schemas/SaleRedirectResponse'
                    UNDEFINED: '#/components/schemas/SaleUndefinedResponse'

components:
  schemas:
    SaleRequest:
      type: object
      required:
        - action
        - client_key
        - order_id
        - order_amount
        - order_currency
        - order_description
        - payer_first_name
        - payer_last_name
        - payer_address
        - payer_country
        - payer_city
        - payer_zip
        - payer_email
        - payer_phone
        - payer_ip
        - term_url_3ds
        - card_number
        - card_exp_month
        - card_exp_year
        - card_cvv2
        - hash
      properties:
        action:
          type: string
          enum: [SALE]
          description: Action type, fixed value "SALE"
        client_key:
          type: string
          format: uuid
          description: Unique client key
        channel_id:
          type: string
          maxLength: 16
          description: Payment channel (Sub-account), optional
        order_id:
          type: string
          maxLength: 255
          description: Transaction ID in Merchant system
        order_amount:
          type: number
          description: >
            Amount of the transaction.
            Format depends on currency exponent.
        order_currency:
          type: string
          minLength: 3
          maxLength: 3
          description: 3-letter currency code
        order_description:
          type: string
          maxLength: 1024
          description: Description of the transaction
        req_token:
          type: string
          enum: [Y, N]
          default: N
          description: Special attribute for tokenization request
        card_token:
          type: string
          maxLength: 64
          description: Credit card token (optional)
        card_number:
          type: string
          description: Credit Card Number; optional if card_token/payment_token specified
        card_exp_month:
          type: string
          pattern: "^(0[1-9]|1[0-2])$"
          description: Expiry month (MM)
        card_exp_year:
          type: string
          pattern: "^[0-9]{4}$"
          description: Expiry year (YYYY)
        card_cvv2:
          type: string
          pattern: "^[0-9]{3,4}$"
          description: CVV code; optional if payment_token specified
        digital_wallet:
          type: string
          enum: [googlepay, applepay]
          description: Digital wallet provider
        payment_token:
          type: string
          description: Token from digital wallet; ignored if card_token present
        payer_first_name:
          type: string
          maxLength: 32
          description: Customer's first name
        payer_last_name:
          type: string
          maxLength: 32
          description: Customer's last name
        payer_middle_name:
          type: string
          maxLength: 32
          description: Customer's middle name
        payer_birth_date:
          type: string
          format: date
          description: Customer's birthday (yyyy-MM-dd)
        payer_address:
          type: string
          maxLength: 255
          description: Customer's address
        payer_address2:
          type: string
          maxLength: 255
          description: Additional address info
        payer_house_number:
          type: string
          maxLength: 9
          description: House/building number
        payer_country:
          type: string
          minLength: 2
          maxLength: 2
          description: 2-letter country code
        payer_state:
          type: string
          maxLength: 32
          description: State or region
        payer_city:
          type: string
          maxLength: 40
          description: City
        payer_district:
          type: string
          maxLength: 32
          description: District of city
        payer_zip:
          type: string
          maxLength: 10
          description: ZIP/postal code
        payer_email:
          type: string
          maxLength: 256
          format: email
          description: Customer's email
        payer_phone:
          type: string
          maxLength: 32
          description: Customer's phone number
        payer_ip:
          type: string
          format: ipv4
          description: IP address (IPv4 or IPv6)
        term_url_3ds:
          type: string
          maxLength: 1024
          format: uri
          description: URL for 3D-Secure return
        term_url_target:
          type: string
          maxLength: 1024
          description: Browsing context name for 3DS return (_blank, _self, _parent, _top or iframe name)
        recurring_init:
          type: string
          enum: [Y, N]
          default: N
          description: Initialization flag for recurring payments
        schedule_id:
          type: string
          description: Schedule ID for recurring payments
        auth:
          type: string
          enum: [Y, N]
          default: N
          description: If 'Y', perform AUTH only (authorization without capture)
        parameters:
          type: object
          additionalProperties:
            type: string
          description: Extra parameters required by acquirer
        custom_data:
          type: object
          additionalProperties:
            type: string
          description: Custom data duplicating arbitrary parameters
        hash:
          type: string
          description: Signature to validate request

    BaseSaleResponse:
      type: object
      properties:
        action:
          type: string
          enum: [SALE]
          description: Action type
        result:
          type: string
          description: Result of transaction
        status:
          type: string
          description: Status of transaction
        order_id:
          type: string
          description: Merchant's transaction ID
        trans_id:
          type: string
          description: Payment Platform transaction ID
        trans_date:
          type: string
          format: date-time
          description: Transaction date in Payment Platform
        descriptor:
          type: string
          description: Descriptor on bank statement

    SaleSuccessResponse:
      allOf:
        - $ref: '#/components/schemas/BaseSaleResponse'
        - type: object
          properties:
            result:
              type: string
              enum: [SUCCESS]
            recurring_token:
              type: string
              description: Recurring token for recurring sales
            schedule_id:
              type: string
              description: Schedule ID if used
            card_token:
              type: string
              description: Card token if req_token was enabled
            amount:
              type: number
              description: Order amount
            currency:
              type: string
              description: Currency code
            digital_wallet:
              type: string
              enum: [googlepay, applepay]
            pan_type:
              type: string
              description: Digital payment card type (DPAN/FPAN)

    SaleDeclinedResponse:
      allOf:
        - $ref: '#/components/schemas/BaseSaleResponse'
        - type: object
          properties:
            result:
              type: string
              enum: [DECLINED]
            amount:
              type: number
              description: Order amount
            currency:
              type: string
              description: Currency code
            decline_reason:
              type: string
              description: Reason for decline
            digital_wallet:
              type: string
              enum: [googlepay, applepay]
            pan_type:
              type: string
              description: Digital payment card type (DPAN/FPAN)

    SaleRedirectResponse:
      allOf:
        - $ref: '#/components/schemas/BaseSaleResponse'
        - type: object
          properties:
            result:
              type: string
              enum: [REDIRECT]
            amount:
              type: number
              description: Order amount
            currency:
              type: string
              description: Currency code
            redirect_url:
              type: string
              format: uri
              description: URL to redirect customer
            redirect_params:
              type: object
              additionalProperties:
                type: string
              description: 3DS redirect parameters
            redirect_method:
              type: string
              enum: [POST, GET]
              description: Method of redirect parameters transfer
            digital_wallet:
              type: string
              enum: [googlepay, applepay]
            pan_type:
              type: string
              description: Digital payment card type (DPAN/FPAN)

    SaleUndefinedResponse:
      allOf:
        - $ref: '#/components/schemas/BaseSaleResponse'
        - type: object
          properties:
            result:
              type: string
              enum: [UNDEFINED]
            amount:
              type: number
              description: Order amount
            currency:
              type: string
              description: Currency code
            custom_data:
              type: object
              additionalProperties:
                type: string
              description: Custom data duplicating arbitrary parameters
            digital_wallet:
              type: string
              enum: [googlepay, applepay]
            pan_type:
              type: string
              description: Digital payment card type (DPAN/FPAN)
/capture:
    post:
      tags:
        - S2S Card
      summary: Capture previously authorized transaction
      operationId: captureTransaction
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CaptureRequest'
      responses:
        '200':
          description: Capture transaction response
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: '#/components/schemas/CaptureSuccessResponse'
                  - $ref: '#/components/schemas/CaptureDeclinedResponse'
                  - $ref: '#/components/schemas/CaptureUndefinedResponse'
                discriminator:
                  propertyName: result
                  mapping:
                    SUCCESS: '#/components/schemas/CaptureSuccessResponse'
                    DECLINED: '#/components/schemas/CaptureDeclinedResponse'
                    UNDEFINED: '#/components/schemas/CaptureUndefinedResponse'

components:
  schemas:
    CaptureRequest:
      type: object
      required:
        - action
        - client_key
        - trans_id
        - amount
        - hash
      properties:
        action:
          type: string
          enum: [CAPTURE]
          example: CAPTURE
        client_key:
          type: string
          format: uuid
          example: 123e4567-e89b-12d3-a456-426614174000
        trans_id:
          type: string
          format: uuid
          example: 789e1234-e89b-12d3-a456-426614174999
        amount:
          type: string
          description: |
            Format depends on currency.
            Examples:
            - Zero-exponent: `1000`
            - 2-exp: `100.00`
            - 3-exp: `100.999`
            - 4-exp: `100.9999`
        hash:
          type: string
          description: Special signature to validate your request

    CaptureSuccessResponse:
      type: object
      properties:
        action:
          type: string
          enum: [CAPTURE]
        result:
          type: string
          enum: [SUCCESS]
        status:
          type: string
          enum: [SETTLED]
        amount:
          type: string
        order_id:
          type: string
        trans_id:
          type: string
          format: uuid
        trans_date:
          type: string
          format: date-time
        descriptor:
          type: string
        currency:
          type: string

    CaptureDeclinedResponse:
      type: object
      properties:
        action:
          type: string
          enum: [CAPTURE]
        result:
          type: string
          enum: [DECLINED]
        status:
          type: string
          enum: [PENDING]
        order_id:
          type: string
        trans_id:
          type: string
          format: uuid
        trans_date:
          type: string
          format: date-time
        descriptor:
          type: string
        amount:
          type: string
        currency:
          type: string
        decline_reason:
          type: string

    CaptureUndefinedResponse:
      type: object
      properties:
        action:
          type: string
          enum: [CAPTURE]
        result:
          type: string
          enum: [UNDEFINED]
        status:
          type: string
          enum: [PENDING]
        order_id:
          type: string
        trans_id:
          type: string
          format: uuid
        trans_date:
          type: string
          format: date-time
        descriptor:
          type: string
        amount:
          type: string
        currency:
          type: string
