openapi: 3.0.3
info:
  title: Payment Platform - Deschedule API
  version: 1.0.0
  description: >
    This API is used to stop recurring payments by descheduling a recurring setup.
    The request is made via POST (e.g., using PHP CURL).

paths:
  /post:
    post:
      tags:
        - S2S Card
      summary: Deschedule Recurring
      operationId: recurring_deschedule
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              required:
                - action
                - client_key
                - recurring_token
                - schedule_id
                - hash
              properties:
                action:
                  type: string
                  enum: [DESCHEDULE]
                  description: Fixed value "DESCHEDULE"
                  example: DESCHEDULE
                client_key:
                  type: string
                  format: uuid
                  description: Unique client identifier
                  example: "123e4567-e89b-12d3-a456-426614174000"
                recurring_token:
                  type: string
                  format: uuid
                  description: Token obtained during the primary transaction
                  example: "999e4567-e89b-12d3-a456-426614174888"
                schedule_id:
                  type: string
                  format: uuid
                  description: Schedule ID in the Payment Platform
                  example: "321e4567-e89b-12d3-a456-426614174999"
                hash:
                  type: string
                  description: Request signature (see Appendix A, Formula 4)
                  example: "hashsignatureabcdef0987654321"

      responses:
        '200':
          description: Deschedule request accepted
          content:
            application/json:
              schema:
                type: object
                properties:
                  action:
                    type: string
                    example: DESCHEDULE
                  result:
                    type: string
                    example: SUCCESS
