openapi: 3.0.3
info:
  title: Payment Platform - Pause Schedule API
  version: 1.0.0
  description: >
    This API is used to pause a payment schedule. It sets the "paused" parameter to "Y".
    The request is made via POST (e.g., using PHP CURL).

paths:
  /post:
    post:
      tags:
        - S2S Card
      summary: Pause Recurring Schedule
      operationId: recurring_pause_schedule
      description: Suspends the schedule and assigns value "Y" for the "paused" parameter.
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              required:
                - action
                - client_key
                - schedule_id
                - hash
              properties:
                action:
                  type: string
                  enum: [PAUSE_SCHEDULE]
                  description: Fixed value "PAUSE_SCHEDULE"
                  example: PAUSE_SCHEDULE
                client_key:
                  type: string
                  format: uuid
                  description: Unique key identifying the client
                  example: "123e4567-e89b-12d3-a456-426614174000"
                schedule_id:
                  type: string
                  format: uuid
                  description: Schedule ID in the Payment Platform
                  example: "321e4567-e89b-12d3-a456-426614174999"
                hash:
                  type: string
                  description: Request signature (see Appendix A, Formula 4)
                  example: "hashsignature1234567890abcdef"

      responses:
        '200':
          description: Successful pause response
          content:
            application/json:
              schema:
                type: object
                properties:
                  action:
                    type: string
                    example: PAUSE_SCHEDULE
                  result:
                    type: string
                    example: SUCCESS
