openapi: 3.0.0
info:
  title: Recurring Payments API
  version: 1.0.0
paths:
  /post:
    post:
      tags:
        - s2s card
      summary: Recurring Sale
      operationId: recurring_sale
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                action:
                  type: string
                  description: Recurring sale type. Always set to 'RECURRING_SALE'.
                  example: "RECURRING_SALE"
                client_key:
                  type: string
                  description: Unique client identifier provided by the payment platform (UUID format).
                  example: "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
                order_id:
                  type: string
                  description: Transaction ID in the merchant's system (up to 255 characters).
                  example: "order_123456789"
                order_amount:
                  type: string
                  description: Amount of the transaction. Format depends on currency. Use Integer for zero-exponent currencies (e.g., 1000), Float for others (e.g., 100.99 for 2-exponent, 100.999 for 3-exponent, 100.9999 for 4-exponent). 'UGX', 'JPY', 'KRW', 'CLP' must use format XX.XX (e.g., 100.00).
                  example: "100.00"
                order_currency:
                  type: string
                  description: Currency of the transaction (e.g., USD).
                  example: "USD"
                order_description:
                  type: string
                  description: Description of the transaction (product or service), up to 1024 characters.
                  example: "Example product description"
                card_number:
                  type: string
                  description: Card number for the transaction.
                  example: "4111111111111111"
                card_exp_month:
                  type: string
                  description: Expiry month of the card (MM format).
                  example: "12"
                card_exp_year:
                  type: string
                  description: Expiry year of the card (YYYY format).
                  example: "2030"
                card_cvv2:
                  type: string
                  description: CVV2 security code of the card.
                  example: "999"
                payer_first_name:
                  type: string
                  description: First name of the payer.
                  example: "Alice"
                payer_last_name:
                  type: string
                  description: Last name of the payer.
                  example: "Doe"
                payer_middle_name:
                  type: string
                  description: Middle name of the payer (optional).
                  example: "Marie"
                payer_birth_date:
                  type: string
                  description: Birth date of the payer (YYYY-MM-DD).
                  example: "1990-01-01"
                payer_address:
                  type: string
                  description: Address of the payer.
                  example: "123 Main St"
                payer_address2:
                  type: string
                  description: Additional address line (optional).
                  example: "Suite 100"
                payer_country:
                  type: string
                  description: Country of the payer (ISO 3166-1 alpha-2 code).
                  example: "US"
                payer_state:
                  type: string
                  description: State or province of the payer.
                  example: "CA"
                payer_city:
                  type: string
                  description: City of the payer.
                  example: "San Francisco"
                payer_zip:
                  type: string
                  description: ZIP or postal code of the payer.
                  example: "94105"
                payer_email:
                  type: string
                  description: Email address of the payer.
                  example: "user@example.com"
                payer_phone:
                  type: string
                  description: Phone number of the payer.
                  example: "+1234567890"
                payer_ip:
                  type: string
                  description: IP address of the payer.
                  example: "192.168.1.1"
                term_url_3ds:
                  type: string
                  description: URL to redirect the customer after 3D Secure authentication.
                  example: "https://example.com/redirect"
                hash:
                  type: string
                  description: Signature hash for validating the request. See Appendix A, Formula 1.
                  example: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
                recurring_init:
                  type: string
                  description: Indicates if this is an initial recurring transaction. Set to 'Y'.
                  example: "Y"
                req_token:
                  type: string
                  description: Flag to return a token in the response. Set to 'Y' if required.
                  example: "Y"
                auth:
                  type: string
                  description: Indicates if transaction should be authorized only ('Y') or captured immediately ('N', default).
                  example: "Y"
                card_token:
                  type: string
                  description: Tokenized representation of the card, returned from a previous transaction.
                  example: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
              required:
                - action
                - client_key
                - order_id
                - order_amount
                - order_currency
                - order_description
                - card_number
                - card_exp_month
                - card_exp_year
                - card_cvv2
                - payer_first_name
                - payer_last_name
                - payer_country
                - payer_ip
                - term_url_3ds
                - hash
                - recurring_init
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  action:
                    type: string
                  result:
                    type: string
                  status:
                    type: string
                  order_id:
                    type: string
                  trans_id:
                    type: string
                  trans_date:
                    type: string
                  amount:
                    type: string
                  currency:
                    type: string
                  card_token:
                    type: string
                  redirect_url:
                    type: string
                  redirect_params:
                    type: object
                    properties:
                      body:
                        type: string
                  redirect_method:
                    type: string
              examples:
                recurring_init_non3ds:
                  summary: Recurring INIT NON3DS
                  value:
                    action: "RECURRING_SALE"
                    result: "SUCCESS"
                    status: "SETTLED"
                    order_id: "order_123456789"
                    trans_id: "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
                    trans_date: "2025-06-08 10:20:43"
                    amount: "100.00"
                    currency: "USD"
                    card_token: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
                initial_recurring_3ds:
                  summary: Initial Recurring 3DS
                  value:
                    action: "RECURRING_SALE"
                    result: "REDIRECT"
                    status: "REDIRECT"
                    order_id: "order_987654321"
                    trans_id: "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
                    trans_date: "2025-06-08 10:24:09"
                    amount: "50.00"
                    currency: "USD"
                    redirect_url: "https://example.com/collector/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
                    redirect_params:
                      body: "REDACTED_BODY"
                    redirect_method: "POST"
                initial_recurring_auth_non3ds:
                  summary: Initial Recurring AUTH NON3DS
                  value:
                    action: "RECURRING_SALE"
                    result: "SUCCESS"
                    status: "PENDING"
                    order_id: "order_1122334455"
                    trans_id: "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
                    trans_date: "2025-06-08 10:26:29"
                    amount: "75.50"
                    currency: "USD"
                initial_recurring_auth_3ds:
                  summary: Initial Recurring AUTH 3DS
                  value:
                    action: "RECURRING_SALE"
                    result: "REDIRECT"
                    status: "REDIRECT"
                    order_id: "order_9988776655"
                    trans_id: "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
                    trans_date: "2025-06-08 10:24:09"
                    amount: "60.00"
                    currency: "USD"
                    redirect_url: "https://example.com/collector/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
                    redirect_params:
                      body: "REDACTED_BODY"
                    redirect_method: "POST"
