openapi: 3.0.3
info:
  title: Payment Platform API - GET_TRANS_STATUS
  version: 1.0.0
  description: |
    Retrieves the status of a transaction from the Payment Platform.
    This request must be sent via HTTP POST (e.g., PHP cURL).
    
    ⚠️ Notes:
    - When using cascading payments, a unique order_id is required per payment.
    - GET_TRANS_STATUS with trans_id returns the status of a specific payment in the cascade.
    - For the final status, rely on callbacks and enable 'Cascading Context for Get Status' in configuration.
    
    Statuses returned: 3DS, REDIRECT, PENDING, PREPARE, DECLINED, SETTLED, REVERSAL, REFUND, VOID, CHARGEBACK.

paths:
  /post:
    post:
      tags:
        - S2S Card
      summary: Get Transaction Status
      operationId: get_trans_status
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              required:
                - action
                - client_key
                - trans_id
                - hash
              properties:
                action:
                  type: string
                  enum: [GET_TRANS_STATUS]
                  description: Fixed action parameter for this request
                  example: GET_TRANS_STATUS
                client_key:
                  type: string
                  format: uuid
                  description: Unique client key (UUID format)
                  example: 550e8400-e29b-41d4-a716-446655440000
                trans_id:
                  type: string
                  format: uuid
                  description: Transaction ID in the Payment Platform
                  example: 66624eba-9e10-11ec-aa41-0242ac130002
                hash:
                  type: string
                  description: Request signature for validation (see Appendix A)
                  example: d41d8cd98f00b204e9800998ecf8427e
      responses:
        "200":
          description: Transaction status response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetTransStatusResponse'
              examples:
                success:
                  summary: Sample successful response
                  value:
                    action: GET_TRANS_STATUS
                    result: SUCCESS
                    status: SETTLED
                    order_id: "1646655381neural"
                    trans_id: "66624eba-9e10-11ec-aa41-0242ac130002"
                    digital_wallet: googlepay

components:
  schemas:
    GetTransStatusResponse:
      type: object
      required:
        - action
        - result
        - status
        - order_id
        - trans_id
      properties:
        action:
          type: string
          enum: [GET_TRANS_STATUS]
          description: Action name
          example: GET_TRANS_STATUS
        result:
          type: string
          enum: [SUCCESS]
          description: Result of the request
          example: SUCCESS
        status:
          type: string
          description: Transaction status
          enum:
            - 3DS
            - REDIRECT
            - PENDING
            - PREPARE
            - DECLINED
            - SETTLED
            - REVERSAL
            - REFUND
            - VOID
            - CHARGEBACK
          example: SETTLED
        order_id:
          type: string
          description: Merchant's transaction ID
          example: "1646655381neural"
        trans_id:
          type: string
          format: uuid
          description: Transaction ID in the Payment Platform
          example: "66624eba-9e10-11ec-aa41-0242ac130002"
        decline_reason:
          type: string
          description: Reason for decline (only for DECLINED status)
          example: Insufficient funds
        recurring_token:
          type: string
          description: Token for recurring payments (present if conditions met)
          example: "tok_123456789"
        schedule_id:
          type: string
          description: Schedule ID for recurring payments
          example: "sch_987654321"
        digital_wallet:
          type: string
          description: Digital wallet provider (e.g., googlepay, applepay)
          example: googlepay
